name: baiduPush
on:
  push:
    branches: [ master, baiduPush ]
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: manual triggered workflow
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Baidu Push
        run: curl -H 'Content-Type:text/plain' --data-binary @urls.txt "${{ secrets.BAIDU_TOKEN }}"
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
