name: vuepress-deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action 🛎️
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
           owner: qcyblm
           repository: https://github.com/qcyblm/qcyblm.github.io.git
           access-token: ${{ secrets.ACCESS_TOKEN }}
        env:
          TZ: Asia/Shanghai
      - name: Setup Node.js environment ⚙️
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.17.0"
      - name: Install and Build 🔧
        run: yarn
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          git-config-name: qcyblm
          git-config-email: ${{ secrets.ACCESS_EMAIL }}
          folder: src/.vuepress/dist
